-- =============================================================================
-- Migration 002 — Create candidates table
-- Description : Stores candidate profiles. Each candidate has a unique,
--               case-insensitive name enforced via the CITEXT extension.
-- Depends on  : 001 (pgcrypto, citext extensions)
-- Idempotent  : Yes
-- =============================================================================

CREATE TABLE IF NOT EXISTS candidates (
    -- Primary key — UUID generated by the application layer via gen_random_uuid()
    id          UUID        NOT NULL DEFAULT gen_random_uuid(),

    -- Case-insensitive unique name (CITEXT compares 'Jane' = 'jane')
    name        CITEXT      NOT NULL,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT candidates_pkey        PRIMARY KEY (id),

    -- Uniqueness is case-insensitive because the column type is CITEXT
    CONSTRAINT candidates_name_unique UNIQUE (name)
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- Supports partial name searches (ILIKE / LIKE with lower())
CREATE INDEX IF NOT EXISTS idx_candidates_name
    ON candidates (name);

-- ---------------------------------------------------------------------------
-- Comments
-- ---------------------------------------------------------------------------

COMMENT ON TABLE  candidates      IS 'Candidate profiles managed by interviewers.';
COMMENT ON COLUMN candidates.id   IS 'UUID primary key, generated by the application.';
COMMENT ON COLUMN candidates.name IS 'Case-insensitive unique display name of the candidate.';
