import { pool } from '../config/db.js';
import type { Candidate } from '../types/index.js';

// ---------------------------------------------------------------------------
// Row type — matches the column names returned by PostgreSQL
// ---------------------------------------------------------------------------

interface CandidateRow {
  id: string;
  name: string;
  created_at: Date;
  updated_at: Date;
}

// ---------------------------------------------------------------------------
// Mapper — converts a raw DB row to a Candidate plain object
// ---------------------------------------------------------------------------

function toCandidate(row: CandidateRow): Candidate {
  return {
    id:        row.id,
    name:      row.name,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

// ---------------------------------------------------------------------------
// Repository methods
// ---------------------------------------------------------------------------

/**
 * Insert a new candidate. The UUID and timestamps are generated by the DB.
 * Throws if the name already exists (UNIQUE constraint on candidates.name).
 */
export async function create(name: string): Promise<Candidate> {
  const { rows } = await pool.query<CandidateRow>(
    `INSERT INTO candidates (name)
     VALUES ($1)
     RETURNING id, name, created_at, updated_at`,
    [name],
  );

  return toCandidate(rows[0]!);
}

/**
 * Find a single candidate by their UUID.
 * Returns null if no candidate with that ID exists.
 */
export async function findById(id: string): Promise<Candidate | null> {
  const { rows } = await pool.query<CandidateRow>(
    `SELECT id, name, created_at, updated_at
     FROM candidates
     WHERE id = $1`,
    [id],
  );

  return rows[0] ? toCandidate(rows[0]) : null;
}

/**
 * Find a single candidate by name (case-insensitive via CITEXT column).
 * Returns null if no match is found.
 */
export async function findByName(name: string): Promise<Candidate | null> {
  const { rows } = await pool.query<CandidateRow>(
    `SELECT id, name, created_at, updated_at
     FROM candidates
     WHERE name = $1`,
    [name],
  );

  return rows[0] ? toCandidate(rows[0]) : null;
}

/**
 * Return all candidates ordered alphabetically by name.
 */
export async function findAll(): Promise<Candidate[]> {
  const { rows } = await pool.query<CandidateRow>(
    `SELECT id, name, created_at, updated_at
     FROM candidates
     ORDER BY name ASC`,
  );

  return rows.map(toCandidate);
}
