import { pool } from '../config/db.js';
import type { Candidate } from '../types/index.js';

// ---------------------------------------------------------------------------
// Row type — matches the column names returned by PostgreSQL
// ---------------------------------------------------------------------------

interface CandidateRow {
  id: string;
  name: string;
  created_at: Date;
  updated_at: Date;
}

// ---------------------------------------------------------------------------
// Mapper — converts a raw DB row to a Candidate plain object
// ---------------------------------------------------------------------------

function toCandidate(row: CandidateRow): Candidate {
  return {
    id: row.id,
    name: row.name,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

// ---------------------------------------------------------------------------
// Repository methods
// ---------------------------------------------------------------------------

/**
 * Insert a new candidate. The UUID and timestamps are generated by the DB.
 * Throws if the name already exists (UNIQUE constraint on candidates.name).
 */
export async function create(name: string, ownerId?: string | null): Promise<Candidate> {
  const { rows } = await pool.query<CandidateRow>(
    `INSERT INTO candidates (name, owner_id)
     VALUES ($1, $2)
     RETURNING id, name, created_at, updated_at`,
    [name, ownerId ?? null],
  );

  return toCandidate(rows[0]!);
}

/**
 * Find a single candidate by their UUID.
 * Returns null if no candidate with that ID exists.
 */
export async function findById(id: string, ownerId?: string | null): Promise<Candidate | null> {
  const values: unknown[] = [id];
  let where = `WHERE id = $1`;

  if (ownerId) {
    values.push(ownerId);
    where += ` AND owner_id = $${values.length}`;
  }

  const { rows } = await pool.query<CandidateRow>(
    `SELECT id, name, created_at, updated_at
     FROM candidates
     ${where}`,
    values,
  );

  return rows[0] ? toCandidate(rows[0]) : null;
}

/**
 * Find a single candidate by name (case-insensitive via CITEXT column).
 * Returns null if no match is found.
 */
export async function findByName(name: string, ownerId?: string | null): Promise<Candidate | null> {
  const values: unknown[] = [name];
  let where = `WHERE name = $1`;

  if (ownerId) {
    values.push(ownerId);
    where += ` AND owner_id = $${values.length}`;
  }

  const { rows } = await pool.query<CandidateRow>(
    `SELECT id, name, created_at, updated_at
     FROM candidates
     ${where}`,
    values,
  );

  return rows[0] ? toCandidate(rows[0]) : null;
}

/**
 * Return all candidates ordered alphabetically by name.
 */
export async function findAll(ownerId?: string | null): Promise<Candidate[]> {
  if (ownerId) {
    const { rows } = await pool.query<CandidateRow>(
      `SELECT id, name, created_at, updated_at
       FROM candidates
       WHERE owner_id = $1
       ORDER BY name ASC`,
      [ownerId],
    );
    return rows.map(toCandidate);
  }

  const { rows } = await pool.query<CandidateRow>(
    `SELECT id, name, created_at, updated_at
     FROM candidates
     ORDER BY name ASC`,
  );

  return rows.map(toCandidate);
}
