import { pool } from '../config/db.js';
import type { Question } from '../types/index.js';

// ---------------------------------------------------------------------------
// Row type — matches the column names returned by PostgreSQL
// ---------------------------------------------------------------------------

interface QuestionRow {
  id: string;
  question_text: string;
  expected_answer: string;
  topic: string;
  is_deleted: boolean;
  created_at: Date;
  updated_at: Date;
}

// ---------------------------------------------------------------------------
// Mapper — converts a raw DB row to a Question plain object
// ---------------------------------------------------------------------------

function toQuestion(row: QuestionRow): Question {
  return {
    id:             row.id,
    questionText:   row.question_text,
    expectedAnswer: row.expected_answer,
    topic:          row.topic,
    isDeleted:      row.is_deleted,
    createdAt:      row.created_at,
    updatedAt:      row.updated_at,
  };
}

// ---------------------------------------------------------------------------
// Repository methods
// ---------------------------------------------------------------------------

/**
 * Insert a new question. UUID and timestamps are generated by the DB.
 */
export async function create(
  questionText: string,
  expectedAnswer: string,
  topic: string,
): Promise<Question> {
  const { rows } = await pool.query<QuestionRow>(
    `INSERT INTO questions (question_text, expected_answer, topic)
     VALUES ($1, $2, $3)
     RETURNING id, question_text, expected_answer, topic, is_deleted, created_at, updated_at`,
    [questionText, expectedAnswer, topic],
  );

  return toQuestion(rows[0]!);
}

/**
 * Find a single active (non-deleted) question by its UUID.
 * Returns null if not found or soft-deleted.
 */
export async function findById(id: string): Promise<Question | null> {
  const { rows } = await pool.query<QuestionRow>(
    `SELECT id, question_text, expected_answer, topic, is_deleted, created_at, updated_at
     FROM questions
     WHERE id = $1
       AND is_deleted = FALSE`,
    [id],
  );

  return rows[0] ? toQuestion(rows[0]) : null;
}

/**
 * Return all active (non-deleted) questions ordered by topic then question text.
 */
export async function findAll(): Promise<Question[]> {
  const { rows } = await pool.query<QuestionRow>(
    `SELECT id, question_text, expected_answer, topic, is_deleted, created_at, updated_at
     FROM questions
     WHERE is_deleted = FALSE
     ORDER BY topic ASC, question_text ASC`,
  );

  return rows.map(toQuestion);
}

/**
 * Return all active questions that belong to a specific topic.
 * The match is case-insensitive (ILIKE).
 */
export async function findByTopic(topic: string): Promise<Question[]> {
  const { rows } = await pool.query<QuestionRow>(
    `SELECT id, question_text, expected_answer, topic, is_deleted, created_at, updated_at
     FROM questions
     WHERE topic ILIKE $1
       AND is_deleted = FALSE
     ORDER BY question_text ASC`,
    [topic],
  );

  return rows.map(toQuestion);
}

/**
 * Soft-delete a question by setting is_deleted = TRUE.
 * The row is preserved so historical review snapshots remain intact.
 * Returns true if a row was updated, false if the id was not found.
 */
export async function deleteById(id: string): Promise<boolean> {
  const { rowCount } = await pool.query(
    `UPDATE questions
     SET is_deleted = TRUE
     WHERE id = $1
       AND is_deleted = FALSE`,
    [id],
  );

  return (rowCount ?? 0) > 0;
}
